/**
 * 
 */
package euler;

/**
 * @date Mar 15, 2017
 */

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5,
 * 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence
 * whose values do not exceed four million, find the sum of the even-valued
 * terms.
 */
public class P002 implements Euler{
	public static void main(String args[]) {
		
		System.out.println(new P002().run());
	}

	/* (non-Javadoc)
	 * @see euler.Euler#run()
	 */
	@Override
	public String run() {
		int limit = 4000000;
		int first = 1;
		int second = 2;
		int sum = 0;

		while (first <= limit) {
			if (first % 2 == 0) {
				sum += first;
			}

			int third = first + second;
			first = second;
			second = third;
		}

		return Integer.toString(sum);
	}
}
